export const ORDER_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
  PENDING_MANUAL_REVIEW: "PENDING_MANUAL_REVIEW",
  INVALID: "INVALID",
};

export const ORDER_CALL_STATUS = {
  QUEUED: "QUEUED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  RETRY_SCHEDULED: "RETRY_SCHEDULED",
  FAILED: "FAILED",
  WHATSAPP_SENT: "WHATSAPP_SENT",
};

export const GENERAL_CALL_STATUS = {
  PENDING: "pending",
  CALLING: "calling",
  ANSWERED: "answered",
  FAILED: "failed",
  RETRYING: "retrying",
};

export const CALL_INTENT = {
  CONFIRM: "CONFIRM",
  CANCEL: "CANCEL",
  BUSY: "BUSY",
  RECALL_REQUEST: "RECALL_REQUEST",
  NO_RESPONSE: "NO_RESPONSE",
  WRONG_NUMBER: "WRONG_NUMBER",
};

export const ORDER_MAX_RETRIES = 100;
export const GENERAL_MAX_RETRIES = 3;

